FORMAT: 1A

# Nektria Routing

The Routing Service of RECS API is designed to elaborate and plan optimized deliveries. First, the merchant can identify and 
minimize delivery bottlenecks using our real time incentive proposals for the shoppers. Then, once all the orders have been 
passed, he can retrieve the optimized route to execute the deliveries.

The API is organized in 4 main areas:
- Base Types are defined in the first part, and are made available with requests to validate their elements.
- Configuration and Assets are designed for the day to day management of the client resources used to execute deliveries.
- Service Requests allow to adapt real time proposals so that the shopper is invited to choose delivery time slots that best suits the delivery planning.
- Optimization requests aim to provide optimal routes for executing the deliveries.

## Security

### Secure communication

All api requests must use https.

### Authentication Schemes

+ Basic (apikey)

    You must provide an API key, which is a unique identifier for your account, as well as an application identifier that helps to
    track which of your applications is making calls to the API.
    + Headers
        + Authorization: Basic YourApiKey


##Group Base Types
## Address [/check/address]
An address contains information about a physical address for pick-up and delivery pruposes

+ Attributes (object)
    + postal_code: 08022 (required, string)
    + street_type: Pza. (optional, string)
    + street_name: Urquinaona (optional, string)
    + street_number: 5 (optional, string)
    + floor: "4º" (optional, string), 
    + door: "1ª" (optional, string), 
    + stair_building: "Escalera A" (optional, string),
    + city: Barcelona (optional, string)
    + country_code: ES (required, string)
    + elevator: 1 (optional, number) 
    + coordinates (optional)
        + latitude: 41.123456 (required, number)
        + longitude: 2.123456 (required, number)

### Check if an Address is valid [POST /check/address]
+ Attributes (Address)
        
+ Response 204
    
+ Response 400 (application/json)
    Invalid Address
    + Body
    
            {
                "status": "error",
                "error": "The address is invalid"
            }
    

## Product [/check/product]

+ Attributes (object)
    + name: box (required, string) - should be set to box when box estimate
    + type: dry (required, string) - dry or cold, describes the type of product
    + quantity: 8 (required, number)
    + quantity_estimated: true (optional, boolean)
    + weight_kg: 4.5 (optional, number)

### Check if a Product is valid [POST /check/product]
+ Attributes (Product)
+ Response 204
            
+ Response 400 (application/json)
    Invalid Product / malformatted
    + Body
    
            {
                "status": "error",
                "error": "The product is missing weight information"
            }

## Shopper [/check/shopper]

+ Attributes (object)
    + shopper_number: KCWS5492344 (required, string) - shopper identifyer in client system
    + name: David (required, string) - name of the shopper
    + surname: Lopez (required, string) - surname of the shopper
    + email: david.lopez@gmail.com (required, string) - surname of the shopper
    + phone: 665 005 493 (required, string) - surname of the shopper

### Check if Shopper is valid [POST /check/shopper]
+ Attributes (Shopper)

+ Response 204
            
+ Response 400 (application/json)
    Invalid Shopper / malformatted
    + Body
    
            {
                "status": "error",
                "error": "The shopper misses name information"
            }
            
## Warehouse [/check/warehouse]

+ Attributes (object)
    + id: 9b4cdc19-bc39-4e53-bda7-f828070f233e (required, string) - warehouse uuid
    + area: CASTILLA (required, string) - area covered by this warehouse
    + location (required, Address) - warehouse location

### Check if Warehouse is valid [POST /check/warehouse]
+ Attributes (Shopper)

+ Response 204
            
+ Response 400 (application/json)
    Invalid Warehouse / malformatted
    + Body
    
            {
                "status": "error",
                "error": "The warehouse should have a location"
            }

## Capacity [/check/capacity]

+ Attributes (object)
    + type: dry (required, string) - dry or cold, describes the type of product it can hold
    + quantity: 8 (required, number) - describes the number of products it can hold

### Check if a Capacity is valid [POST /check/capacity]
+ Attributes (Capacity)

+ Response 204
            
+ Response 400 (application/json)
    Invalid Product / malformatted
    + Body
    
            {
                "status": "error",
                "error": "The capacity is missing quantity information"
            }


## TimeWindow [/time_windows] 

+ Attributes (object)
    + `start_time`: `2016-03-29T15:19:00+01:00` (required, string) ISO8601 time at which the window starts
    + `end_time`: `2016-03-29T15:37:00+01:00` (required, string) ISO8601 time at which the window ends

### Check if a Time Window is valid [POST /check/time_window]
+ Attributes (TimeWindow)

+ Response 204
            
+ Response 400 (application/json)
    Invalid Time Window
    + Body
    
            {
                "status": "error",
                "error": "start time is earlier than end time"
            }

## TimeWindowCost [/time_window_costs] 

+ Attributes (object)
    + `start_time`: `2016-03-29T15:19:00+01:00` (required, string) ISO8601 time at which the window starts
    + `end_time`: `2016-03-29T15:37:00+01:00` (required, string) ISO8601 time at which the window ends
    + `cost`: 90 (required, number) relative estimated cost of delivery during this time window, between 0 and 100.
    + `final_price`: 9 (required, number) the final price that is recomended for transportation
    + `currency_code`: EUR (required, string) 3 letter currency code corresponding to this price
    + `logistic_cost`: 120 (required, number) the estimated difficulty for performing this delivery, as a percentage
    + `full`: false (required, boolean) has this window reached estimated delivery capacity?
    + `free`: false (required, boolean) should this window be proposed for free?
    + `closed`: false (required, boolean) should this window be closed for reasons that are not related to delivery capacity?
    + `eco`: false (optional, boolean) should this window be proposed as ECO?
    + `preselected`: false (optional, boolean) set to true if this is the default selection for the user.
    + `external_id`: XHK-78932 (optional, string) identifier, if it was provided in the request with time windows

### Check if a Time Window Cost is valid [POST /check/time_window_cost]
+ Attributes (TimeWindowCost)

+ Response 204
            
+ Response 400 (application/json)
    Invalid Time Window Cost
    + Body
    
            {
                "status": "error",
                "error": "Invalid cost 'low'"
            }

## GridTimeWindow [/grid_time_windows] 

+ Attributes (object)
    + `start_time`: `2016-03-29T15:19:00+01:00` (required, string) ISO8601 time at which the window starts
    + `end_time`: `2016-03-29T15:37:00+01:00` (required, string) ISO8601 time at which the window ends
    + `free`: false (required, boolean) is this time slot proposed for free?
    + `full`: false (required, boolean) has this time slot reached maximum capacity?
    + `closed`: false (required, boolean) is this time slot closed?
    + `extra_order`: false (optional, boolean) is this slot the delivery slot of another order for this client? Default value is false.
    + `price`: 9.00 (required, number) shipping price of this slot
    + `currency_code`: EUR (required, string) 3 letter currency code corresponding to this price
    + `capacity` (required)
        + `max`: `20` (required, number) time slot's maximum capacity
        + `used`: `11` (required, number) capacity already used for this time slot
        + `daily_max`: `200` (optional, number) maximum capacity of this day
        + `daily_used`: `87` (optional, number) capacity already in use this day
    + `external_id`: XHK-78932 (optional, string) identifier for short access to this time window in the response

### Check if a Grid Time Window is valid [POST /check/grid_time_window]
+ Attributes (GridTimeWindow)
+ Response 204


##Group Configuration & Assets

## VehicleCategory [/vehicle_categories]    

+ Attributes (object)
    + `name`: TRUCK_3500 (required, string) name of the vehicle category
    

### Check if a Vehicle Category is valid [POST /check/vehicle_category]
+ Attributes (VehicleCategory)
+ Response 204
            
+ Response 400 (application/json)
    Invalid VehicleCategory
    + Body
    
            {
                "status": "error",
                "error": "Unknown option speed"
            }

### List Vehicles Category [GET /vehicles?name={name}&limit={limit}&offset={offset}]
+ Parameters
    + limit (optional, number) - Default 10, from 1 to 100. Number of returned values.
    + name: TRUCK_3500 (optional, string) - Filter the vehicle category by name
    + offset (optional, number) - Default 0. Postion of the first returned record.

+ Response 200 (application/json)
    + Attributes 
        + list (array[VehicleCategory])


## Vehicle [/vehicle]   

+ Attributes (object)
    + `vehicle_number`: BCN_VAN_1 (optional, string)
    + capacity (required, array[Capacity]) - list describing transportation areas of the vehicle
    + type: van (optional, string)
    + options (optional) 
        + efficiency: 1.2 (optional, number)
        + helpers: 1 (optional, number)
    + `vehicle_category`: TRUCK_3500 (required, string) name of the vehicle category related

### Check if a Vehicle is valid [POST /check/vehicle]
+ Attributes (Vehicle)
+ Response 204
            
+ Response 400 (application/json)
    Invalid Vehicle
    + Body
    
            {
                "status": "error",
                "error": "Unknown option speed"
            }

## Area [/areas]    

+ Attributes (object)
    + `id`: 29 (required, string)
    + `name`: BCN (optional, string)
    + `postal_codes` (optional, array)

### Check if an Area is valid [POST /check/area]

    + Attributes (Area)
    + Body

            {
                "id" : "11",
                "name": "BCN",
                "postal_codes": [
                    "08001", 
                    "08002", 
                    "08003", 
                    "08004", 
                    "08005", 
                    "08006"
                ]
            }

+ Response 204
            
+ Response 400 (application/json)
    Invalid Area
    + Body
    
            {
                "status": "error",
                "error": "Incorrect postal code"
            }

### List Areas [GET /areas?limit={limit}&offset={offset}]
+ Parameters
    + limit (optional, number) - Default 10, from 1 to 100. Number of returned values.
    + offset (optional, number) - Default 0. Postion of the first returned record.

+ Response 200 (application/json)
    + Attributes 
        + list (array[Area])
    
            list of areas

### Get an Area [GET /areas/{area_id}]
+ Parameters
    + area_id (required, string) - The Area Id
+ Response 200 (application/json)
    + Attributes (Area)

##Group Services

## RoutingService [/services/routing]

+ Attributes (object)
    + id (required, string) - Routing service uuid    
    + price: 131.47 (required, number) - shopping cart total price
    + currency_code: EUR (required, string) - 3 letters currency code corresponding to the price
    + destination (required, Address) - Submitted delivery address
    + products (required, array[Product]) - Submitted list of products
    + origin (optional, Address) - Submitted overriding default Warehouse address
    + availability (required, boolean) is there some delivery option available ?
    + `custom_delivery_windows` (optional, array[GridTimeWindow]) - delivery windows with details of initial situation whenever they were submitted
    + `proposed_delivery_windows` (required, array[TimeWindowCost])
    + `selected_delivery_windows` (optional, array[TimeWindow])
    + status (required, string) - requested, validated, confirmed or cancelled
    + priority (optional, number) - priority of the resulting order, on a scale from 1 (high) to 10 (low).
    + order (optional, Order) - customer order details
    + created_date (required, string) - date the service has been created, in format YYYY-mm-dd
    + confirmed_date (optional, string) - date the service has been confirmed, in format YYYY-mm-dd
    + shopper (optional, Shopper) - details about the eCommerce client
    

### List Routing Services [GET /services/routing?offset={offset}&limit={limit}&status={status}&availability={availability}&created_date={created_date}&confirmed_date={confirmed_date}]
+ Parameters
    + offset (optional, number) - Default 0. Postion of the first returned record.
    + limit (optional, number) - Default 10, from 1 to 100. Number of returned values.
    + status (optional, string) - requested, validated, confirmed or cancelled
    + availability (optional, boolean) - do we have available delivery options ?
    + created_date (optional, string) - date of service creation, in format YYYY-mm-dd
    + confirmed_date(optional, string) - date of service confirmation, in format YYYY-mm-dd

+ Response 200 (application/json)
    + Attributes 
        + list (array[RoutingService])
        
    + Body
    
            {
            "list":[
            {
                "id": "25baa73d-1345-4075-8ad9-81f20daeb555",
                "availability": true,
                "status": "requested",
                "created_date": "2016-05-12",
                "destination": {
                    "postal_code": "08022",
                    "street_type": "Pza.",
                    "street_name": "Urquinaona",
                    "street_number": "5",
                    "city": "Barcelona",
                    "country_code": "ES",
                    "elevator": true,
                    "coordinates": {
                      "latitude": 41.123456,
                      "longitude": 2.123456
                    }
                },
              "products": [
                {
                  "name": "box",
                  "quantity": 8,
                  "weight_kg": 4.5
                }
              ],
                "proposed_delivery_windows": [
                    {
                        "start_time": "2016-03-14T07:00:00+0100",
                        "end_time": "2016-03-14T09:00:00+0100",
                        "cost": 76
                    },
                    {
                        "start_time": "2016-03-14T08:00:00+0100",
                        "end_time": "2016-03-14T10:00:00+0100",
                        "cost": 77
                    },
                    {
                        "start_time": "2016-03-14T09:00:00+0100",
                        "end_time": "2016-03-14T11:00:00+0100",
                        "preselected": true,
                        "cost": 71
                    },
                    {
                        "start_time": "2016-03-14T10:00:00+0100",
                        "end_time": "2016-03-14T12:00:00+0100",
                        "cost": 80
                    },
                    {
                        "start_time": "2016-03-14T11:00:00+0100",
                        "end_time": "2016-03-14T13:00:00+0100",
                        "cost": 93
                    }
                ]
            }
            ]
                
            }

### Create Routing Service [POST /services/routing]

+ Request (application/json)

+ Attributes
    + destination (required, Address)
    + products (required, array[Product])
    + origin (optional, Address) - Overrides the default Warehouse address
    + `custom_delivery_windows` (required, array[GridTimeWindow]) - delivery windows with details of initial situation
    + price: 131.47 (required, number) - shopping cart total price
    + currency_code: EUR (required, string) - 3 letters currency code corresponding to the price
    + shopper_number: KCWS5492344 (optional, string) - [deprecated] shopper identifyer in client system
    + shopper (optional, Shopper) - information about the shopper
    + priority (optional, number) - priority of the resulting order, on a scale from 1 (high) to 10 (low).

+ Response 201 (application/json)
  Service has been successfully requested
    
    + Attributes
        + RoutingService

    + Body
    
            {
                "id": "25baa73d-1345-4075-8ad9-81f20daeb555",
                "availability": true,
                "status": "requested",
                "created_date": "2016-05-12",
                "price" : 85.35,
                "currency_code": "EUR",
                "shopper": {
                    "shopper_number": "OBNP-690360",
                    "name": "David",
                    "surname": "Lopez",
                    "email": "david.lopez@gmail.com",
                    "phone": "665 005 493"
                },
                "destination": {
                    "postal_code": "08022",
                    "street_type": "Pza.",
                    "street_name": "Urquinaona",
                    "street_number": "5",
                    "city": "Barcelona",
                    "country_code": "ES",
                    "elevator": true,
                    "coordinates": {
                      "latitude": 41.123456,
                      "longitude": 2.123456
                    }
                },
              "products": [
                {
                  "name": "box",
                  "quantity": 8,
                  "weight_kg": 4.5
                }
              ],
              "custom_delivery_windows": [
                    {
                    
                        "start_time": "2016-03-14T08:00:00+0100",
                        "end_time": "2016-03-14T09:00:00+0100",
                        "price": 9,
                        "currency_code": "EUR",
                        "free": false,
                        "full": false,
                        "closed": false,
                        "capacity":
                        {
                            "max": 6,
                            "used": 3,
                            "daily_max": 110,
                            "daily_used": 52
                        },
                        "external_id": "8603603"
                    },
                    {
                        "start_time": "2016-03-14T09:00:00+0100",
                        "end_time": "2016-03-14T10:00:00+0100",
                        "price": 9,
                        "currency_code": "EUR",
                        "free": false,
                        "full": false,
                        "closed": false,
                        "capacity":
                        {                            
                            "max": 6,
                            "used": 2,
                            "daily_max": 110,
                            "daily_used": 52                            
                        },
                        "external_id": "8603604"
                    },
                    {
                        "start_time": "2016-03-14T10:00:00+0100",
                        "end_time": "2016-03-14T11:00:00+0100",
                        "price": 9,
                        "currency_code": "EUR",
                        "free": false,
                        "full": false,
                        "closed": false,
                        "capacity":
                        {
                            "max": 6,
                            "used": 0,                            
                            "daily_max": 110,
                            "daily_used": 52                            
                        },
                        "external_id": "8603605"
                    },
                    {
                        "start_time": "2016-03-14T11:00:00+0100",
                        "end_time": "2016-03-14T12:00:00+0100",
                        "price": 9,
                        "currency_code": "EUR",
                        "free": false,
                        "full": false,
                        "closed": false,
                        "capacity":
                        {
                            "max": 6,
                            "used": 3,                            
                            "daily_max": 110,
                            "daily_used": 52                            
                        },
                        "external_id": "8603606"
                    },
                    {
                        "start_time": "2016-03-14T12:00:00+0100",
                        "end_time": "2016-03-14T13:00:00+0100",
                        "price": 9,
                        "currency_code": "EUR",
                        "free": false,
                        "full": false,
                        "closed": false,
                        "capacity":
                        {
                            "max": 6,
                            "used": 1,                            
                            "daily_max": 110,
                            "daily_used": 52                            
                        },
                        "external_id": "8603607"
                    }
                ],
                "proposed_delivery_windows": [
                    {
                        "start_time": "2016-03-14T08:00:00+0100",
                        "end_time": "2016-03-14T09:00:00+0100",
                        "cost": 76,
                        "external_id": "8603603"
                    },
                    {
                        "start_time": "2016-03-14T09:00:00+0100",
                        "end_time": "2016-03-14T10:00:00+0100",
                        "cost": 77,
                        "external_id": "8603604"
                    },
                    {
                        "start_time": "2016-03-14T10:00:00+0100",
                        "end_time": "2016-03-14T11:00:00+0100",
                        "cost": 71,
                        "preselected": true,
                        "external_id": "8603605"
                    },
                    {
                        "start_time": "2016-03-14T11:00:00+0100",
                        "end_time": "2016-03-14T12:00:00+0100",
                        "cost": 80,
                        "external_id": "8603606"
                    },
                    {
                        "start_time": "2016-03-14T12:00:00+0100",
                        "end_time": "2016-03-14T13:00:00+0100",
                        "cost": 93,
                        "external_id": "8603607"
                    }
                ]
            }
            

### Create Routing Service  with Deferred Availability [POST /services/routing/create-with-deferred-availability]

+ Request (application/json)

+ Attributes
    + destination (required, Address) - Known information about destination address
    + origin (optional, Address) - Overrides the default Warehouse address
    + `custom_delivery_windows` (required, array[TimeWindow]) - delivery windows to be taken into account

+ Response 201 (application/json)
  Service has been successfully requested
    
    + Attributes
        + RoutingService

    + Body
    
            {
                "id": "25baa73d-1345-4075-8ad9-81f20daeb555",
                "status": "prerequested",
                "created_date": "2016-05-12",
                "destination": {
                    "postal_code": "08022",
                    "country_code": "ES"
                },
              "custom_delivery_windows": [
                    {
                    
                        "start_time": "2016-03-14T08:00:00+0100",
                        "end_time": "2016-03-14T09:00:00+0100"
                    },
                    {
                        "start_time": "2016-03-14T09:00:00+0100",
                        "end_time": "2016-03-14T10:00:00+0100"
                    },
                    {
                        "start_time": "2016-03-14T10:00:00+0100",
                        "end_time": "2016-03-14T11:00:00+0100"
                    },
                    {
                        "start_time": "2016-03-14T11:00:00+0100",
                        "end_time": "2016-03-14T12:00:00+0100"
                    },
                    {
                        "start_time": "2016-03-14T12:00:00+0100",
                        "end_time": "2016-03-14T13:00:00+0100"
                    }
                ]
            }

### Retrieve Routing Service Availability [PATCH /services/routing/{service_id}/retrieve-availability]

+ Parameters
    + service_id (required, string)

+ Request (application/json)

+ Attributes
    + destination (required, Address)
    + products (required, array[Product])
    + origin (optional, Address) - Overrides the default Warehouse address
    + `custom_delivery_windows` (required, array[GridTimeWindow]) - delivery windows with details of initial situation
    + price: 131.47 (required, number) - shopping cart total price
    + currency_code: EUR (required, string) - 3 letters currency code corresponding to the price
    + shopper_number: KCWS5492344 (optional, string) - [deprecated] shopper identifyer in client system
    + shopper (optional, Shopper) - information about the shopper
    + priority (optional, number) - priority of the resulting order, on a scale from 1 (high) to 10 (low).

+ Response 201 (application/json)
  Service has been successfully requested
    
    + Attributes
        + RoutingService

    + Body
    
            {
                "id": "25baa73d-1345-4075-8ad9-81f20daeb555",
                "availability": true,
                "status": "requested",
                "created_date": "2016-05-12",
                "price" : 85.35,
                "currency_code": "EUR",
                "shopper": {
                    "shopper_number": "OBNP-690360",
                    "name": "David",
                    "surname": "Lopez",
                    "email": "david.lopez@gmail.com",
                    "phone": "665 005 493"
                },
                "destination": {
                    "postal_code": "08022",
                    "street_type": "Pza.",
                    "street_name": "Urquinaona",
                    "street_number": "5",
                    "city": "Barcelona",
                    "country_code": "ES",
                    "elevator": true,
                    "coordinates": {
                      "latitude": 41.123456,
                      "longitude": 2.123456
                    }
                },
              "products": [
                {
                  "name": "box",
                  "quantity": 8,
                  "weight_kg": 4.5
                }
              ],
              "custom_delivery_windows": [
                    {
                    
                        "start_time": "2016-03-14T08:00:00+0100",
                        "end_time": "2016-03-14T09:00:00+0100",
                        "price": 9,
                        "currency_code": "EUR",
                        "free": false,
                        "full": false,
                        "closed": false,
                        "capacity":
                        {
                            "max": 6,
                            "used": 3,
                            "daily_max": 110,
                            "daily_used": 52
                        },
                        "external_id": "8603603"
                    },
                    {
                        "start_time": "2016-03-14T09:00:00+0100",
                        "end_time": "2016-03-14T10:00:00+0100",
                        "price": 9,
                        "currency_code": "EUR",
                        "free": false,
                        "full": false,
                        "closed": false,
                        "capacity":
                        {                            
                            "max": 6,
                            "used": 2,
                            "daily_max": 110,
                            "daily_used": 52                            
                        },
                        "external_id": "8603604"
                    },
                    {
                        "start_time": "2016-03-14T10:00:00+0100",
                        "end_time": "2016-03-14T11:00:00+0100",
                        "price": 9,
                        "currency_code": "EUR",
                        "free": false,
                        "full": false,
                        "closed": false,
                        "capacity":
                        {
                            "max": 6,
                            "used": 0,                            
                            "daily_max": 110,
                            "daily_used": 52                            
                        },
                        "external_id": "8603605"
                    },
                    {
                        "start_time": "2016-03-14T11:00:00+0100",
                        "end_time": "2016-03-14T12:00:00+0100",
                        "price": 9,
                        "currency_code": "EUR",
                        "free": false,
                        "full": false,
                        "closed": false,
                        "capacity":
                        {
                            "max": 6,
                            "used": 3,                            
                            "daily_max": 110,
                            "daily_used": 52                            
                        },
                        "external_id": "8603606"
                    },
                    {
                        "start_time": "2016-03-14T12:00:00+0100",
                        "end_time": "2016-03-14T13:00:00+0100",
                        "price": 9,
                        "currency_code": "EUR",
                        "free": false,
                        "full": false,
                        "closed": false,
                        "capacity":
                        {
                            "max": 6,
                            "used": 1,                            
                            "daily_max": 110,
                            "daily_used": 52                            
                        },
                        "external_id": "8603607"
                    }
                ],
                "proposed_delivery_windows": [
                    {
                        "start_time": "2016-03-14T08:00:00+0100",
                        "end_time": "2016-03-14T09:00:00+0100",
                        "cost": 76,
                        "external_id": "8603603"
                    },
                    {
                        "start_time": "2016-03-14T09:00:00+0100",
                        "end_time": "2016-03-14T10:00:00+0100",
                        "cost": 77,
                        "external_id": "8603604"
                    },
                    {
                        "start_time": "2016-03-14T10:00:00+0100",
                        "end_time": "2016-03-14T11:00:00+0100",
                        "cost": 71,
                        "preselected": true,
                        "external_id": "8603605"
                    },
                    {
                        "start_time": "2016-03-14T11:00:00+0100",
                        "end_time": "2016-03-14T12:00:00+0100",
                        "cost": 80,
                        "external_id": "8603606"
                    },
                    {
                        "start_time": "2016-03-14T12:00:00+0100",
                        "end_time": "2016-03-14T13:00:00+0100",
                        "cost": 93,
                        "external_id": "8603607"
                    }
                ]
            }
            
### Create Routing Service With Custom Delivery Windows [POST /services/routing/create-with-custom-delivery-windows]

+ Request (application/json)

+ Attributes
    + destination (required, Address)
    + products (required, array[Product])
    + origin (optional, Address) - Overrides the default Warehouse address
    + `custom_delivery_windows` (required, array[GridTimeWindow]) - delivery windows with details of initial situation
    + price: 131.47 (required, number) - shopping cart total price
    + currency_code: EUR (required, string) - 3 letters currency code corresponding to the price
    + shopper_number: KCWS5492344 (optional, string) - [deprecated] shopper identifyer in client system
    + shopper (optional, Shopper) - information about the shopper
    + priority (optional, number) - priority of the resulting order, on a scale from 1 (high) to 10 (low).

+ Response 201 (application/json)
  Service has been successfully requested
    
    + Attributes
        + RoutingService

    + Body
    
            {
                "id": "25baa73d-1345-4075-8ad9-81f20daeb555",
                "availability": true,
                "status": "requested",
                "created_date": "2016-05-12",
                "price" : 85.35,
                "currency_code": "EUR",
                "shopper": {
                    "shopper_number": "OBNP-690360",                
                    "name": "David",
                    "surname": "Lopez",
                    "email": "david.lopez@gmail.com",
                    "phone": "665 005 493"
                },
                "destination": {
                    "postal_code": "08022",
                    "street_type": "Pza.",
                    "street_name": "Urquinaona",
                    "street_number": "5",
                    "city": "Barcelona",
                    "country_code": "ES",
                    "elevator": true,
                    "coordinates": {
                      "latitude": 41.123456,
                      "longitude": 2.123456
                    }
                },
              "products": [
                {
                  "name": "box",
                  "quantity": 8,
                  "weight_kg": 4.5
                }
              ],
              "custom_delivery_windows": [
                    {
                    
                        "start_time": "2016-03-14T08:00:00+0100",
                        "end_time": "2016-03-14T09:00:00+0100",
                        "price": 9,
                        "currency_code": "EUR",
                        "free": false,
                        "full": false,
                        "closed": false,
                        "capacity":
                        {
                            "max": 6,
                            "used": 3,
                            "daily_max": 110,
                            "daily_used": 52
                        },
                        "external_id": "8603603"
                    },
                    {
                        "start_time": "2016-03-14T09:00:00+0100",
                        "end_time": "2016-03-14T10:00:00+0100",
                        "price": 9,
                        "currency_code": "EUR",
                        "free": false,
                        "full": false,
                        "closed": false,
                        "capacity":
                        {                            
                            "max": 6,
                            "used": 2,
                            "daily_max": 110,
                            "daily_used": 52                            
                        },
                        "external_id": "8603604"
                    }
                ],
                "proposed_delivery_windows": [
                    {
                        "start_time": "2016-03-14T11:00:00+0100",
                        "end_time": "2016-03-14T12:00:00+0100",
                        "cost": 80,
                        "external_id": "8603606"
                    },
                    {
                        "start_time": "2016-03-14T12:00:00+0100",
                        "end_time": "2016-03-14T13:00:00+0100",
                        "cost": 93,
                        "external_id": "8603607"
                    }
                ]
            }
        

### Book Routing Service [PATCH /services/routing/{service_id}/book]

+ Parameters
    + service_id (required, string)

+ Request (application/json)

        {
            "delivery_windows":[
                {
                    "start_time": "2016-03-14T19:00:00+0100",
                    "end_time": "2016-03-14T21:00:00+0100"
                }
            ]
        }

+ Attributes
    + delivery_windows (required, array[TimeWindow]) - the selected delivery time windows

+ Response 200 (application/json)
  Service has been successfully requested
    
    + Attributes
        + RoutingService

    + Body
    
            {
                "id": "25baa73d-1345-4075-8ad9-81f20daeb555",
                "availability": true,
                "status": "booked",
                "created_date": "2016-05-12",
                "destination": {
                    "postal_code": "08022",
                    "street_type": "Pza.",
                    "street_name": "Urquinaona",
                    "street_number": "5",
                    "city": "Barcelona",
                    "country_code": "ES",
                    "elevator": true,
                    "coordinates": {
                      "latitude": 41.123456,
                      "longitude": 2.123456
                    }
                },
              "products": [
                {
                  "name": "box",
                  "quantity": 8,
                  "weight_kg": 4.5
                }
              ],
                "proposed_delivery_windows": [
                    {
                        "start_time": "2016-03-14T07:00:00+0100",
                        "end_time": "2016-03-14T09:00:00+0100",
                        "cost": 76
                    },
                    {
                        "start_time": "2016-03-14T08:00:00+0100",
                        "end_time": "2016-03-14T10:00:00+0100",
                        "cost": 77
                    },
                    {
                        "start_time": "2016-03-14T09:00:00+0100",
                        "end_time": "2016-03-14T11:00:00+0100",
                        "preselected":true,
                        "cost": 71
                    },
                    {
                        "start_time": "2016-03-14T10:00:00+0100",
                        "end_time": "2016-03-14T12:00:00+0100",
                        "cost": 80
                    },
                    {
                        "start_time": "2016-03-14T11:00:00+0100",
                        "end_time": "2016-03-14T13:00:00+0100",
                        "cost": 93
                    }
                ],
                "selected_delivery_windows":[
                    {
                        "start_time": "2016-03-14T07:00:00+0100",
                        "end_time": "2016-03-14T09:00:00+0100"
                    }
                ]
            }
            
### Confirm Routing Service [PATCH /services/routing/{service_id}/confirm]

+ Parameters
    + service_id (required, string)

+ Request (application/json)

        {
            "order_number": "LP22842-U",
            "delivery_windows":[
                {
                    "start_time": "2016-03-14T19:00:00+0100",
                    "end_time": "2016-03-14T21:00:00+0100"
                }
            ]
        }
        
+ Attributes
        + order_number (required, string) - the order number created by the eCommerce
        + delivery_windows (required, array[TimeWindow]) - the selected delivery time windows
        
+ Response 200 (application/json)
  Service has been successfully requested
    
    + Attributes
        + RoutingService

    + Body
    
            {
                "id": "25baa73d-1345-4075-8ad9-81f20daeb555",
                "availability": true,
                "status": "confirmed",
                "created_date": "2016-05-12",
                "destination": {
                    "postal_code": "08022",
                    "street_type": "Pza.",
                    "street_name": "Urquinaona",
                    "street_number": "5",
                    "city": "Barcelona",
                    "country_code": "ES",
                    "elevator": true,
                    "coordinates": {
                      "latitude": 41.123456,
                      "longitude": 2.123456
                    }
                },
              "products": [
                {
                  "name": "box",
                  "quantity": 8,
                  "weight_kg": 4.5
                }
              ],
                "proposed_delivery_windows": [
                    {
                        "start_time": "2016-03-14T07:00:00+0100",
                        "end_time": "2016-03-14T09:00:00+0100",
                        "cost": 76
                    },
                    {
                        "start_time": "2016-03-14T08:00:00+0100",
                        "end_time": "2016-03-14T10:00:00+0100",
                        "cost": 77
                    },
                    {
                        "start_time": "2016-03-14T09:00:00+0100",
                        "end_time": "2016-03-14T11:00:00+0100",
                        "preselected": true,
                        "cost": 71
                    },
                    {
                        "start_time": "2016-03-14T10:00:00+0100",
                        "end_time": "2016-03-14T12:00:00+0100",
                        "cost": 80
                    },
                    {
                        "start_time": "2016-03-14T11:00:00+0100",
                        "end_time": "2016-03-14T13:00:00+0100",
                        "cost": 93
                    }
                ],
                "selected_delivery_windows":[
                    {
                        "start_time": "2016-03-14T07:00:00+0100",
                        "end_time": "2016-03-14T09:00:00+0100"
                    }
                ],
                "order": {
                    "id": "a3634d36-3fa2-11e7-a8c6-ac87a32559ad",
                    "shift": "ee18de70-2c4e-11e7-a3b0-24cc1c381f6d",
                    "order_number": "815593001495534535",
                    "destination": {
                        "postal_code": "08022",
                        "street_type": "Pza.",
                        "street_name": "Urquinaona",
                        "street_number": "5",
                        "city": "Barcelona",
                        "country_code": "ES",
                        "elevator": true,
                        "coordinates": {
                          "latitude": 41.123456,
                          "longitude": 2.123456
                        }
                    },
                    "products": [
                      {
                        "name": "items",
                        "quantity": 23,
                        "type": "generic",
                        "quantity_estimated": false
                      }
                    ]
                },
                "confirmed_date": "2016-05-12"
            }
            


##Group Optimization

## Step [/steps] 

+ Attributes (object)
    + `id` (required, number) step uuid
    + `delivery_window` (required, TimeWindow) order delivery window
    + `order` (required, Order) order coverd by this step
    + `estimated_delivery_time` (optional, string)
    + `estimated_delivery_duration` (optional, string) time spent with the customer in seconds
    + `parking_cost` (number) number of estimated parking seconds
    + `distance_to_arrive` (number) driving distance in meters
    + `time_to_arrive` (number) driving time in seconds
    + `waiting_seconds` (number) number of seconds between parking time and selected delivery time

### Check if a Step is valid [POST /check/step]
+ Attributes (Step)
    
+ Response 204
            
+ Response 400 (application/json)
    Invalid Step
    + Body
    
            {
                "status": "error",
                "error": "unknown order reference"
            }

## Order [/orders]    

+ Attributes (object)
    + `id`: "a08f5828-1630-4afc-aec7-1a172ceb919a" (required, string) order uuid
    + order_number: AA123456 (required, string)
    + products (required, array[Product])
    + origin (optional, Address)
    + destination (required, Address)
    + `delivery_windows` (required, array[TimeWindow])
    + shopper (optional, Shopper) - information about the shopper
    + shift_id (optional, string)
    + status (required, string)
    + priority (optional, number) - priority, on a scale from 1 (high) to 10 (low).
    

### Check if an Order is valid [POST /check/order]
+ Attributes (Order)
+ Response 204
            
+ Response 400 (application/json)
    Invalid Order
    + Body
    
            {
                "status": "error",
                "error": "The order is invalid"
            }
    


### Create an Order [POST /orders]
+ Request (application/json)
+ Attributes (object)
    + order_number: AA123456 (required, string)
    + destination (required, Address)
    + products (array[Product])
    + origin (optional, Address)
    + `delivery_windows` (required, array[TimeWindow])
    + shopper (optional, Shopper) - information about the shopper
    + priority (optional, number) - priority, on a scale from 1 (high) to 10 (low).
    
    
+ Response 201 (application/json)
    Returned on creation success  
    + Attributes (Order)
    + Headers
    
            Location: /orders/{order_id}

+ Response 400
    Returned if there is any parameter missing or with wrong type or format
    + Body
+ Response 409
    Returned if there is already an order with the same order_number
    + Body
+ Response 500
    Returned if an error occurred storing the order
    + Body

### Create an Order for a Shift[POST /orders/create-for-shift]
+ Request (application/json)
+ Attributes (object)
    + order_number: AA123456 (required, string)
    + destination (required, Address)
    + products (array[Product])
    + origin (optional, Address)
    + `delivery_windows` (required, array[TimeWindow])
    + shopper (optional, Shopper) - information about the shopper
    + `shift` (required, string) uuid of the shift the order belongs to
    + priority (optional, number) - priority, on a scale from 1 (high) to 10 (low).
    
+ Response 201 (application/json)
    Returned on creation success  
    + Attributes (Order)
    + Headers
    
            Location: /orders/{order_id}

+ Response 400
    Returned if there is any parameter missing or with wrong type or format
    + Body
+ Response 409
    Returned if there is already an order with the same order_number
    + Body
+ Response 500
    Returned if an error occurred storing the order
    + Body

### List Orders [GET /orders?limit={limit}&offset={offset}&status={status}&order_number={order_number}&created_date={created_date}&delivery_day={delivery_day}]
+ Parameters
    + limit (optional, number) - Default 10, from 1 to 100. Number of returned values.
    + offset (optional, number) - Default 0. Start point of the returned array.
    + status (optional, string) - filter orders by status
    + `order_number` (optional, string) - filter orders by order_number
    + created_date (optional, string) - Date in format YYYY-MM-DD. Filter orders starting from creation date.
    + delivery_day (optional, string) - Date in format YYYY-MM-DD. Filter orders with delivery programmed for delivery day.

+ Response 200 (application/json)

    + Attributes
        + list (array[Order])
        
    + Body
    
            {
                "list": 
                [
                    {
                      "id": "a08f5828-1630-4afc-aec7-1a172ceb919a",
                      "order_number": "AA123456",
                      "destination": {
                        "postal_code": "08022",
                        "street_type": "Pza.",
                        "street_name": "Urquinaona",
                        "street_number": "5",
                        "city": "Barcelona",
                        "country_code": "ES",
                        "elevator": 1,
                        "coordinates": {
                          "latitude": 41.123456,
                          "longitude": 2.123456
                        }
                      },
                      "status": "pending",
                      "delivery_windows": [
                        {
                          "start_time": "2016-03-29T15:19:00+01:00",
                          "end_time": "2016-03-29T15:37:00+01:00"
                        }
                      ],
                      "products": [
                        {
                          "name": "box",
                          "type": "dry",
                          "quantity": 8,
                          "quantity_estimated": true,
                          "weight_kg": 4.5
                        }
                      ],
                      "origin": {
                        "postal_code": "08022",
                        "street_type": "Pza.",
                        "street_name": "Urquinaona",
                        "street_number": "5",
                        "city": "Barcelona",
                        "country_code": "ES",
                        "elevator": 1,
                        "coordinates": {
                          "latitude": 41.123456,
                          "longitude": 2.123456
                        }
                      },
                      "shift": 123
                    },
                    {
                      "id": "53224",
                      "order_number": "AA123678",
                      "destination": {
                        "postal_code": "08022",
                        "street_type": "Pza.",
                        "street_name": "Urquinaona",
                        "street_number": "5",
                        "city": "Barcelona",
                        "country_code": "ES",
                        "elevator": 1,
                        "coordinates": {
                          "latitude": 41.123456,
                          "longitude": 2.123456
                        }
                      },
                      "status": "pending",
                      "delivery_windows": [
                        {
                          "start_time": "2016-03-29T15:19:00+01:00",
                          "end_time": "2016-03-29T15:37:00+01:00"
                        }
                      ],
                      "products": [
                        {
                          "name": "box",
                          "type": "dry",
                          "quantity": 8,
                          "quantity_estimated": true,
                          "weight_kg": 4.5
                        }
                      ],
                      "origin": {
                        "postal_code": "08022",
                        "street_type": "Pza.",
                        "street_name": "Urquinaona",
                        "street_number": "5",
                        "city": "Barcelona",
                        "country_code": "ES",
                        "elevator": 1,
                        "coordinates": {
                          "latitude": 41.123456,
                          "longitude": 2.123456
                        }
                      },
                      "shift": 123,
                      "priority": 3
                    }
                ]
            }
    
+ Response 400 (application/json)
    + Body
    
            [
                "Invalid Data: Incorrect data format: The test_error key is not expected in Nektria\\Recs\\RoutingApiBundle\\Model\\Requests\\Orders\\ListRoutingOrderRequest"
            ]

### Get an Order [GET /orders/{order_id}]
+ Parameters
    + order_id (required, string) - The Order id
+ Response 200 (application/json)
    + Attributes (Order)

### Update an Order [PUT /orders/{order_id}]
+ Request (application/json)
+ Attributes (object)
    + order_number: AA123456 (required, string)
    + destination (required, Address)
    + products (array[Product])
    + origin (optional, Address)
    + `delivery_windows` (required, array[TimeWindow])
    + shopper (optional, Shopper) - information about the shopper
    + priority (optional, number) - priority, on a scale from 1 (high) to 10 (low).
    
+ Response 200 (application/json)
    Update successful
    + Attributes (Order)

+ Response 400
    Returned if there is any parameter missing or with wrong type or format
    + Body
+ Response 404
    Returned if the order is not found in the system
    + Body
+ Response 500
    Returned if an error occurred updating the order
    + Body

### Update an Order for Shift [PUT /orders/{order_id}/update-for-shift]
+ Request (application/json)
+ Attributes (object)
    + order_number: AA123456 (required, string)
    + destination (required, Address)
    + products (array[Product])
    + origin (optional, Address)
    + `delivery_windows` (required, array[TimeWindow])
    + shopper (optional, Shopper) - information about the shopper
    + `shift` (optional, string) id of the shift the order belongs to
    + priority (optional, number) - priority, on a scale from 1 (high) to 10 (low).
    
+ Response 200 (application/json)
    Update successful
    + Attributes (Order)

+ Response 400
    Returned if there is any parameter missing or with wrong type or format
    + Body
+ Response 404
    Returned if the order is not found in the system
    + Body
+ Response 500
    Returned if an error occurred updating the order
    + Body

### Update Order delivery windows [PATCH /orders/{order_id}/reschedule-delivery]
+ Request (application/json)
+ Attributes (object)
    + `delivery_windows` (required, array[TimeWindow])
    + `shift` (required, string) id of the shift the order belongs to

+ Response 200 (application/json)
    Update successful
    + Attributes (Order)

+ Response 400
    Returned if there is any parameter missing or with wrong type or format
    + Body
+ Response 404
    Returned if the order is not found in the system
    + Body
+ Response 500
    Returned if an error occurred updating the order
    + Body

### Update Order gps coordinates [PATCH /orders/{order_id}/replace-destination-gps]
+ Request (application/json)
+ Attributes (object)
    + coordinates (required)
        + latitude: 41.123456 (required, number)
        + longitude: 2.123456 (required, number)
    
+ Response 200 (application/json)
    Update successful
    + Attributes (Order)
        
+ Response 400
    Returned if there is any parameter missing or with wrong type or format
    + Body
+ Response 404
    Returned if the order is not found in the system
    + Body
+ Response 500
    Returned if an error occurred updating the order
    + Body

### Update Order products [PATCH /orders/{order_id}/replace-products]
+ Request (application/json)
+ Attributes (object)
    + products (array[Product])
    
+ Response 200 (application/json)
    Update successful
    + Attributes (Order)

+ Response 400
    Returned if there is any parameter missing or with wrong type or format
    + Body
+ Response 404
    Returned if the order is not found in the system
    + Body
+ Response 500
    Returned if an error occurred updating the order
    + Body

### Deliver an Order [PATCH /orders/{order_id}/deliver]
+ Parameters
    + order_id (required, string) - The id of the Order
    
+ Request (application/json)
    + Attributes (object)
        + `delivery_time`(optional, string)
        + `delivery_duration`(optional, string)

+ Response 200 (application/json)
    Deliver action successful
    + Attributes (Order)

+ Response 400
    There are missing parameters or with wrong type/format
    + Body

+ Response 404
    Returned if there is no order with the specified order_id
    + Body

+ Response 500
    Returned if an error occurred updating the order
    + Body

### Cancel an Order [PATCH /orders/{order_id}/cancel]
+ Parameters
    + order_id (required, id) - The Order id

+ Response 200
    Cancel action successful
    + Attributes (Order)
+ Response 404
    Returned if there is no order with the specified order_id
    + Body

+ Response 500
    Returned if an error occurred deleting the order
    + Body

### Delete an Order [DELETE /orders/{order_id}]
+ Parameters
    + order_id (required, id) - The Order id

+ Response 204

+ Response 404
    Returned if there is no order with the specified order_id
    + Body

+ Response 500
    Returned if an error occurred deleting the order
    + Body
    

## Route [/routes]    

+ Attributes (object)
    + `id`: "58f20afa-098f-4821-a1a2-a8833b4685fd" (required, string) route uuid
    + origin (required, Address)
    + `loading_window` (required, TimeWindow)
    + `execution_window` (required, TimeWindow)
    + vehicle (required, Vehicle)
    + itinerary (required, array[Step])
    + status: done (required, string)

### Check if a Route is valid [POST /check/route]
+ Attributes (Route)
+ Response 204
            
+ Response 400 (application/json)
    Invalid Route
    + Body
    
            {
                "status": "error",
                "error": "Unknown vehicle BCN_VAN_15"
            }

### List Routes [GET /routes?status={status}&limit={limit}]
+ Parameters
    + limit (optional, number) - Default 10, from 1 to 100. Number of returned values.
    + status: pending (optional, string) - Filter the routes by status

+ Response 200 (application/json)
    + Attributes 
        + list (array[Route])

### Get a Route [GET /routes/{route_id}]
+ Parameters
    + route_id (required, string) - The Route uuid
+ Response 200 (application/json)
    + Attributes (Route)

## Shift [/shifts]

A Shift groups the orders of a specific time range and area, and has relationships with the resources that are assigned to fullfill these orders.

+ Attributes (object)
    + id: "6b61eab6-8e65-4e83-b410-ae6c0a397449" (required, string) shift uuid
    + name: `2016-03-29 mañana` (optional, string) Custom name of this shift
    + span (required, TimeWindow)
    + status: pending (required, string) shift status
    + area (required, Area) Area covered by this shift
    + warehouse (required, Warehouse) warehouse serving this shift
    + fleet (required, array[Vehicle]) list of vehicles assigned to this shift
    + main_scenario (optional) 
        + status (required, string) status of the main scenario - created, optimizing, optimized, ongoing or done
        + selected_vehicles (required, array[string]) list of vehicle ids selected for this scenario
    + other_scenarios (optional, array[string]) list of ids of scenarios beside the main senario
    + orders (required, array[string]) list of order uuid assigned to this shift
    

### Create a Shift [POST /shifts]

+ Request (application/json)

+ Attributes
    + name: `2016-03-29 mañana` (optional, string) Custom name of this shift
    + span (required, TimeWindow)
    + area: `bf7976da-ddc7-4801-b8d5-95577f05e411` (required, string) id of the area assigned to this shift
    + fleet (required, array[Vehicle]) list of the vehicles assigned to this shift
    + time_slots (optional, array[TimeWindow]) delivery time windows to be proposed to the shopper
    
+ Response 201 (application/json)
        
        {
            "span":
            {
                "start_time": "2016-03-17T15:00:00+0100",
                "end_time": "2016-03-17T23:00:00+0100"
            },
            "status": "created",
            "area": {
                    "id": "59",
                    "name": "BCN"
            },
            "fleet":
            [
                {
                    "vehicle_number": "BCN_VAN_1",
                    "capacities" : 
                    [
                        {
                            "type": "dry",
                            "quantity": 30
                        },
                        {
                            "type": "cold",
                            "quantity": 30
                        }
                    ],
                    "vehicle_category": "TRUCK_3500"
                }
            ],
            "time_slots":
            [
                {
                    "start_time": "2016-03-17T15:00:00+0100",
                    "end_time": "2016-03-17T27:00:00+0100"
                },
                {
                    "start_time": "2016-03-17T16:00:00+0100",
                    "end_time": "2016-03-17T28:00:00+0100"
                },
                {
                    "start_time": "2016-03-17T16:00:00+0100",
                    "end_time": "2016-03-17T21:00:00+0100"
                }
            ],
            "orders":[]
        }


### List Shifts [GET /shifts?limit={limit}&offset={offset}&expand={expand}&area_id={area_id}&status={status}]

+ Parameters
    + limit (optional, number) - Default 10, from 1 to 100. Number of returned values.
    + offset (optional, number) - Default 0. Start point of the returned array.
    + expand: false (optional, boolean) - When true, returns entire shift objects.
    + area_id: BCN (optional, string) - filter shifts within an area
    + status: pending (optional, string) - filter shift by status

+ Response 200 (application/json)

    + Attributes
        + list (array[Shift])
        
    + Body
    
            {
                "list": [
                    {
                        "id": 1,
                        "name": "2016-03-29 mañana",
                        "span": 
                        {
                            "start_time": "2016-03-14T07:00:00+0100",
                            "end_time": "2016-03-14T15:00:00+0100"
                        },
                        "status": "closed"
                    },
                    {
                        "id": 2,
                        "name": "2016-03-29 tarde",
                        "span":
                        {
                            "start_time": "2016-03-14T15:00:00+0100",
                            "end_time": "2016-03-14T23:00:00+0100"
                        },
                        "status": "pending"
                    }
                ]
            }
            
+ Response 400 (application/json)
    + Body
    
            [
                "Invalid Data: Incorrect data format: The test_error key is not expected in Nektria\\Recs\\RoutingApiBundle\\Model\\Requests\\Shifts\\ListRoutingShiftRequest"
            ]


### Get a Shift [GET /shifts/{shift_id}]

+ Parameters
    + shift_id (required, string) - Id of the shift, retrievable with a GET request.

+ Request (application/json)
        
+ Response 200 (application/json)
        
        {
            "span":
            {
                "start_time": "2016-03-17T15:00:00+0100",
                "end_time": "2016-03-17T23:00:00+0100"
            },
            "status": "optimized",
            "area": {
                    "id": "59",
                    "name": "BCN"
            },
            "fleet":
            [
                {
                    "vehicle_number": "BCN_VAN_1",
                    "capacities" : 
                    [
                        {
                            "type": "dry",
                            "quantity": 30
                        },
                        {
                            "type": "cold",
                            "quantity": 30
                        }
                    ],
                    "vehicle_category": "TRUCK_3500"
                },
                {
                    "vehicle_number": "BCN_VAN_2",
                    "capacities" : 
                    [
                        {
                            "type": "dry",
                            "quantity": 30
                        },
                        {
                            "type": "cold",
                            "quantity": 30
                        }
                    ],
                    "options":
                    {
                        "helpers": 1
                    },
                    "vehicle_category": "TRUCK_3500"
                }
            ],
            "time_slots":
            [
                {
                    "start_time": "2016-03-17T15:00:00+0100",
                    "end_time": "2016-03-17T27:00:00+0100"
                },
                {
                    "start_time": "2016-03-17T16:00:00+0100",
                    "end_time": "2016-03-17T28:00:00+0100"
                },
                {
                    "start_time": "2016-03-17T16:00:00+0100",
                    "end_time": "2016-03-17T21:00:00+0100"
                }
            ],
            "orders":[
                {
                    "id" : "00000000-0000-0000-0000-0000000000",
                    "order_number" : "0000000"
                },
                {
                    "id" : "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
                    "order_number" : "xxxxxxx"
                }
            ]
        }
        
+ Response 404
    Shift does not exist
    + Body

### Assign an Order to a Shift [PATCH /shifts/{shift_id}/add-order]

+ Parameters
    + shift_id (required, string) - Id of the shift, retrievable with a GET request.
    
+ Request (application/json)
    + Attributes
        + order_id (required, string) id of the order that we want to assign
    + Body
    
            {
                "order_id": "48920"
            }
            
+ Response 200 (application/json)
        
        {
            "span":
            {
                "start_time": "2016-03-17T15:00:00+0100",
                "end_time": "2016-03-17T23:00:00+0100"
            },
            "status": "open",
            "area": {
                    "id": "59",
                    "name": "BCN"
            },
            "orders":[48920]
        }
        
+ Response 404
    Shift does not exist
    + Body

### Remove an Order from a Shift [PATCH /shifts/{shift_id}/remove-order]

+ Parameters
    + shift_id (required, string) - Id of the shift, retrievable with a GET request.

+ Request (application/json)
    + Attributes
        + order_id (required, string) id of the order that we want to assign
    + Body
    
            {
                "order_id": "48920"
            }
            
+ Response 200 (application/json)
        
        {
            "span":
            {
                "start_time": "2016-03-17T15:00:00+0100",
                "end_time": "2016-03-17T23:00:00+0100"
            },
            "status": "open",
            "area": {
                    "id": "59",
                    "name": "BCN"
            },
            "orders":[]
        }
        
+ Response 404
    Shift does not exist
    + Body
    

### Close a Shift [PATCH /shifts/{shift_id}/close]

+ Parameters
    + shift_id (required, string)

+ Request (application/json)
        
+ Response 200 (application/json)
    + Attributes
        + id: 123 (required, string) Unique shift identifier
        + name: `2016-03-29 mañana` (optional, string) Custom name of this shift
        + span (required)
            + `start_time`: `2016-03-29T15:19:00+01:00` (required, string) ISO8601 time at which the window starts
            + `end_time`: `2016-03-29T15:37:00+01:00` (required, string) ISO8601 time at which the window ends    
        + status: pending (required, string) shift status
        + area (required, Area) Area covered by this shift
        + fleet (required, array[Vehicle]) list of vehicles assigned to this shift
        + main_scenario (optional) 
            + status (required, string) status of the main scenario - created, optimizing, optimized, ongoing or done
            + selected_vehicles (required, array[string]) list of vehicle ids selected for this scenario
        + other_scenarios (optional, array[string]) list of ids of scenarios beside the main senario
        + time_slots (required, array[TimeWindow]) delivery time windows proposed to the shopper
        + orders (required, array[string]) list of order ids assigned to this shift    
    + Body
    
            {
                "span":
                {
                    "start_time": "2016-03-17T15:00:00+0100",
                    "end_time": "2016-03-17T23:00:00+0100"
                },
                "status": "closed",
                "area": {
                    "id": "59",
                    "name": "BCN"
                },
                "fleet":
                [
                    {
                        "vehicle_number": "BCN_VAN_1",
                        "capacities" : 
                        [
                            {
                                "type": "dry",
                                "quantity": 30
                            },
                            {
                                "type": "cold",
                                "quantity": 30
                            }
                        ],
                        "vehicle_category": "TRUCK_3500"
                    },
                    {
                        "vehicle_number": "BCN_VAN_2",
                        "capacities" : 
                        [
                            {
                                "type": "dry",
                                "quantity": 30
                            },
                            {
                                "type": "cold",
                                "quantity": 30
                            }
                        ],
                        "options":
                        {
                            "helpers": 1
                        },
                        "vehicle_category": "TRUCK_3500"
                    }
                ],
                "time_slots":
                [
                    {
                        "start_time": "2016-03-17T15:00:00+0100",
                        "end_time": "2016-03-17T27:00:00+0100"
                    },
                    {
                        "start_time": "2016-03-17T16:00:00+0100",
                        "end_time": "2016-03-17T28:00:00+0100"
                    },
                    {
                        "start_time": "2016-03-17T16:00:00+0100",
                        "end_time": "2016-03-17T21:00:00+0100"
                    }
                ],
                "orders":["324", "309", "343"]
            }
    
    
+ Response 404

### Reopen a Shift [PATCH /shifts/{shift_id}/reopen]

+ Parameters
    + shift_id (required, string)

+ Request (application/json)
        
+ Response 200 (application/json)
    + Attributes
        + id: "59c73102-3fb5-11e7-8f72-ac87a32559ad" (required, string)  shift uuid
        + name: `2016-03-29 mañana` (optional, string) Custom name of this shift
        + span (required)
            + `start_time`: `2016-03-29T15:19:00+01:00` (required, string) ISO8601 time at which the window starts
            + `end_time`: `2016-03-29T15:37:00+01:00` (required, string) ISO8601 time at which the window ends    
        + status: pending (required, string) shift status
        + area (required, Area) Area covered by this shift
        + fleet (required, array[Vehicle]) list of vehicles assigned to this shift
        + main_scenario (optional) 
            + status (required, string) status of the main scenario - created, optimizing, optimized, ongoing or done
            + selected_vehicles (required, array[string]) list of vehicle ids selected for this scenario
        + other_scenarios (optional, array[string]) list of ids of scenarios beside the main senario
        + time_slots (required, array[TimeWindow]) delivery time windows proposed to the shopper
        + orders (required, array[string]) list of order uuids assigned to this shift    
    + Body
    
            {
                "span":
                {
                    "start_time": "2016-03-17T15:00:00+0100",
                    "end_time": "2016-03-17T23:00:00+0100"
                },
                "status": "closed",
                "area": {
                    "id": "59",
                    "name": "BCN"
                },
                "fleet":
                [
                    {
                        "vehicle_number": "BCN_VAN_1",
                        "capacities" : 
                        [
                            {
                                "type": "dry",
                                "quantity": 30
                            },
                            {
                                "type": "cold",
                                "quantity": 30
                            }
                        ],
                        "vehicle_category": "TRUCK_3500"
                    },
                    {
                        "vehicle_number": "BCN_VAN_2",
                        "capacities" : 
                        [
                            {
                                "type": "dry",
                                "quantity": 30
                            },
                            {
                                "type": "cold",
                                "quantity": 30
                            }
                        ],
                        "options":
                        {
                            "helpers": 1
                        },
                        "vehicle_category": "TRUCK_3500"
                    }
                ],
                "time_slots":
                [
                    {
                        "start_time": "2016-03-17T15:00:00+0100",
                        "end_time": "2016-03-17T27:00:00+0100"
                    },
                    {
                        "start_time": "2016-03-17T16:00:00+0100",
                        "end_time": "2016-03-17T28:00:00+0100"
                    },
                    {
                        "start_time": "2016-03-17T16:00:00+0100",
                        "end_time": "2016-03-17T21:00:00+0100"
                    }
                ],
                "orders":["20e4af75-0e8e-4e1d-8247-b319922fe677", "a34db12c-224b-40fe-9082-84be67a481f0", "4d1ba181-ef17-4d95-acd2-67445d526a0f"]
            }
    
    
+ Response 404

### Optimize Shift Main Scenario [PATCH /shifts/{shift_id}/optimize-main-scenario]

Once the shift optimization has been completed, an event will be triggered.

+ Parameters
    + shift_id (required, string)
        
+ Request (application/json)
        
+ Response 200 (application/json)
    + Attributes
        + id: 4d6078f7-6279-4ca4-9787-637447b943c4 (required, string) Unique shift identifier
        + name: `2016-03-29 mañana` (optional, string) Custom name of this shift
        + span (required)
            + `start_time`: `2016-03-29T15:19:00+01:00` (required, string) ISO8601 time at which the window starts
            + `end_time`: `2016-03-29T15:37:00+01:00` (required, string) ISO8601 time at which the window ends    
        + status: pending (required, string) shift status
        + area (required, Area) Area covered by this shift
        + fleet (required, array[Vehicle]) list of vehicles assigned to this shift
        + main_scenario (optional) 
            + status (required, string) status of the main scenario - created, optimizing, optimized, ongoing or done
            + selected_vehicles (required, array[string]) list of vehicle ids selected for this scenario
        + other_scenarios (optional, array[string]) list of ids of scenarios beside the main senario
        + time_slots (required, array[TimeWindow]) delivery time windows proposed to the shopper
        + orders (required, array[string]) list of order ids assigned to this shift    
    + Body
    
            {
                "span":
                {
                    "start_time": "2016-03-17T15:00:00+0100",
                    "end_time": "2016-03-17T23:00:00+0100"
                },
                "status": "optimizing",
                "area": {
                    "id": "59",
                    "name": "BCN"
                },
                "fleet":
                [
                    {
                        "vehicle_number": "BCN_VAN_1",
                        "capacities" : 
                        [
                            {
                                "type": "dry",
                                "quantity": 30
                            },
                            {
                                "type": "cold",
                                "quantity": 30
                            }
                        ],
                        "vehicle_category": "TRUCK_3500"
                    },
                    {
                        "vehicle_number": "BCN_VAN_2",
                        "capacities" : 
                        [
                            {
                                "type": "dry",
                                "quantity": 30
                            },
                            {
                                "type": "cold",
                                "quantity": 30
                            }
                        ],
                        "options":
                        {
                            "helpers": 1
                        },
                        "vehicle_category": "TRUCK_3500"
                    }
                ],
                "time_slots":
                [
                    {
                        "start_time": "2016-03-17T15:00:00+0100",
                        "end_time": "2016-03-17T27:00:00+0100"
                    },
                    {
                        "start_time": "2016-03-17T16:00:00+0100",
                        "end_time": "2016-03-17T28:00:00+0100"
                    },
                    {
                        "start_time": "2016-03-17T16:00:00+0100",
                        "end_time": "2016-03-17T21:00:00+0100"
                    }
                ],
                "orders":["20e4af75-0e8e-4e1d-8247-b319922fe677", "a34db12c-224b-40fe-9082-84be67a481f0", "4d1ba181-ef17-4d95-acd2-67445d526a0f"]
            }
    
        
+ Response 404

### Update Fleet for a Shift [PUT /shifts/{shift_id}/fleet]

+ Request (application/json)

        [
            {
                "vehicle_number": "BCN_VAN_1",
                "capacities" : 
                [
                    {
                        "type": "dry",
                        "quantity": 30
                    },
                    {
                        "type": "cold",
                        "quantity": 30
                    }
                ],
                "vehicle_category": "TRUCK_3500"
            },
            {
                "vehicle_number": "BCN_VAN_2",
                "capacities" : 
                [
                    {
                        "type": "dry",
                        "quantity": 30
                    },
                    {
                        "type": "cold",
                        "quantity": 30
                    }
                ],
                "options":
                {
                    "helpers": 1
                },
                "vehicle_category": "TRUCK_3500"
            }
        ]

+ Response 200 (application/json)
        
+ Response 404
    Shift does not exist
    + Body

### Get Shift Roadmap [GET /shifts/{shift_id}/roadmap]
        
+ Response 200 (application/json)
        
        {
            "unreached_orders": ["e361be10-f4bf-4896-8cb6-8fb0e80eea63", "359a8f65-0b03-4433-8682-11129236669f"],
            "unused_vehicles": [],
            "routes": 
            [
                {
                    "id": "80cd4323-d8c0-439b-a0ac-3e062459ae95",
                    "delivery_window": 
                    {
                        "start_time": "2016-03-17T09:00:00+0100",
                        "end_time": "2016-03-17T12:15:00+0100"
                    },
                    "vehicle": 
                    {
                        "vehicle_number": "BCN_VAN_1",
                        "capacities" : 
                        [
                            {
                                "type": "dry",
                                "quantity": 30
                            },
                            {
                                "type": "cold",
                                "quantity": 30
                            }
                        ],
                        "vehicle_category": "TRUCK_3500"
                    }
                },
                {
                    "id": "2beac30e-a082-4398-81b3-a1532c86ba3f",
                    "delivery_window": 
                    {
                        "start_time": "2016-03-17T09:10:00+0100",
                        "end_time": "2016-03-17T11:45:00+0100"
                    },
                    "vehicle": 
                    {
                        "vehicle_number": "BCN_VAN_2",
                        "capacities" : 
                        [
                            {
                                "type": "dry",
                                "quantity": 30
                            },
                            {
                                "type": "cold",
                                "quantity": 30
                            }
                        ],
                        "options":
                        {
                            "helpers": 1
                        },
                        "vehicle_category": "TRUCK_3500"
                    }
                }
            ]
        }
        
+ Response 404